### ISSUE TITLE
Setup Authentik

### ISSUE THREAD

**Issue by datend3nker** [bboehmke/grocy-oauth#1]
How  did you setup the Oauthprovider in Authentik. Especially, how did you setup the username claim?

**Comment by bboehmke** [comment]
There are nothing special needed on the authentik site. The user scopes are defined like:
![image](https://github.com/user-attachments/assets/e63dff5b-867d-4c34-ab25-5cbf08e3ff00)

The scopes in the grocy config are 1:1 the same as in the example config in the readme.

I can share my complete config later this day, if needed.

**Comment by datend3nker** [comment]
sry for bothering you. After setting everything up, when opening grocy, the page is only white

**Comment by bboehmke** [comment]
Are there any errors in the logs?

Never the less here my complete config: (I replaced/removed the URL and CLIENT_*)

### docker-compose.yml
```yaml
services:
  grocy:
    # https://github.com/linuxserver/docker-grocy/releases
    image: lscr.io/linuxserver/grocy:v4.2.0-ls266
    restart: unless-stopped
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: "Europe/Berlin"
    volumes:
      - ./data:/config
      - ./OAuthMiddleware.php:/app/www/middleware/OAuthMiddleware.php:ro

    labels:
      traefik.enable: "true"
      traefik.http.routers.grocy.rule: "Host(`grocy.example.com`)"
      traefik.http.routers.grocy.entrypoints: "websecure"
      traefik.http.services.grocy.loadbalancer.server.port: "80"

networks:
  default:
    name: docker_net
    external: true

```

### `config.php`
```php

Setting('AUTH_CLASS', 'Grocy\Middleware\OAuthMiddleware');

// Options when using OAuthMiddleware
Setting('OAUTH_CLIENT_ID', 'XXX');
Setting('OAUTH_CLIENT_SECRET', 'XXX');
Setting('OAUTH_SCOPES', 'openid profile');
Setting('OAUTH_USERNAME_CLAIM', 'preferred_username');
Setting('OAUTH_AUTH_URL', 'https://auth.example.com/application/o/authorize/');
Setting('OAUTH_TOKEN_URL', 'https://auth.example.com/application/o/token/');
Setting('OAUTH_USERINFO_URL', 'https://auth.example.com/application/o/userinfo/');
```

### Authentik OAuth provider
![image](https://github.com/user-attachments/assets/d820c478-2775-473d-938d-12ad816bfd76)
![image](https://github.com/user-attachments/assets/b55b9c32-54a3-4155-bcf8-966a50af7892)
![image](https://github.com/user-attachments/assets/afb5f4fc-29ce-4354-8da6-39248ff637b7)
![image](https://github.com/user-attachments/assets/9bd03d55-c6ac-4cdc-84e2-3ac4ddac9772)
